---
 - hosts: localhost1
   become: yes
   
   tasks:
     - name: install pip
       apt: name: python-pip 
     - name: install virtual env
       apt: virtualenv
     - name: Check that the somefile.conf exists
       stat: path=~/.cloudmesh/
       register: cloudmesh_exists
     - name: Install cloudmesh folder if does not exists
       command: pip install -U cloudmesh_client
       when: cloudmesh_exists.stat.exists == False
     - name: Upgrade cloudmesh if cloudmesh folder exists
       command: cm reset
       command: pip uninstall cloudmesh_client
       command: pip install -U cloudmesh_client
       command: cm refresh on
       command: cm key add —ssh



- name: Install cloudmesh folder if does not exists
       command: pip install -U cloudmesh_client
       when: cloudmesh_exists.stat.exists == False
     - name: Upgrade cloudmesh if cloudmesh folder exists
       command: cm reset
       command: pip uninstall cloudmesh_client
       command: rm -rf ~/
       command: pip install -U cloudmesh_client
       command: cm refresh on
       command: cm key add —ssh
       

- name: Upgrade the cloudmesh client
       sudo: true
       shell: |
	 cm reset
         pip uninstall cloudmesh_client
         pip install -U cloudmesh_client
       when: cloudmesh_exists.stat.exists == True
                
    
   
